/* ============================================================
   Léxico — Currículo (fonte única de verdade)
   Adicionar módulos = adicionar objetos aqui. Nenhum outro
   arquivo precisa mudar para o roadmap/progresso refletirem.
   status: 'next' | 'soon' | 'planned' | 'done'
   path:   'js' | 'ts'
   ============================================================ */
window.LEXICO = window.LEXICO || {};

LEXICO.phases = [
  { id: "fundamentos", n: "Fase 01", path: "js", title: "Pensando como programador", tag: "Fundamentos",
    accent: "#ff6b9d", icon: "🧭",
    desc: "Do zero absoluto: como máquinas executam código e como pensar em problemas." },
  { id: "js-basico",   n: "Fase 02", path: "js", title: "JavaScript básico", tag: "JavaScript",
    accent: "#f2b84b", icon: "✨",
    desc: "Valores, variáveis, fluxo, funções — a gramática essencial da linguagem." },
  { id: "js-inter",    n: "Fase 03", path: "js", title: "JavaScript intermediário", tag: "JavaScript",
    accent: "#5fd08a", icon: "🧱",
    desc: "Escopo, closures, protótipos, arrays de alta ordem, módulos." },
  { id: "js-runtime",  n: "Fase 04", path: "js", title: "Runtime & internals", tag: "Avançado",
    accent: "#b98cff", icon: "⚙️",
    desc: "O que acontece por baixo dos panos: contexto, event loop, memória, async." },
  { id: "web",         n: "Fase 05", path: "js", title: "Web Platform", tag: "Plataforma",
    accent: "#6fb6f5", icon: "🌐",
    desc: "DOM, eventos e as APIs do navegador que dão vida ao JavaScript." },
  { id: "ts-fund",     n: "Fase 06", path: "ts", title: "TypeScript fundamental", tag: "TypeScript",
    accent: "#58b0f0", icon: "🛡️",
    desc: "Tipos como extensão do que você já sabe de JavaScript — não um substituto." },
  { id: "ts-inter",    n: "Fase 07", path: "ts", title: "TypeScript intermediário", tag: "TypeScript",
    accent: "#3dd7c4", icon: "🧩",
    desc: "Interfaces, unions, narrowing e generics: modelar dados com precisão." },
  { id: "ts-avancado", n: "Fase 08", path: "ts", title: "TypeScript avançado", tag: "Type-level",
    accent: "#a78bfa", icon: "🪄",
    desc: "Programação em nível de tipos: conditional, mapped e template literal types." },
  { id: "ts-aplicado", n: "Fase 09", path: "ts", title: "TypeScript aplicado & projeto", tag: "Projeto",
    accent: "#ff8a6b", icon: "🚀",
    desc: "Levar tudo para o mundo real: APIs, bibliotecas e o projeto final." },
];

LEXICO.modules = [
  // ---- Fundamentos (js) ----
  { n: "01", slug: "pensando-como-programador", phase: "fundamentos", path: "js", status: "next",
    title: "Pensando como programador",
    desc: "O coração do curso: aprender a transformar uma ideia em código. Decomposição, padrões, abstração e algoritmo — treinados um a um e reunidos num método repetível.",
    topics: ["Decomposição", "Padrões", "Abstração", "Algoritmo", "Da ideia ao código"] },
  { n: "02", slug: "como-o-codigo-executa", phase: "fundamentos", path: "js", status: "planned",
    title: "Como o código executa",
    desc: "Do texto que você escreve à máquina que roda: engine, runtime e ambiente.",
    topics: ["Engine", "Runtime", "Browser / Node"] },
  { n: "03", slug: "primeiros-passos", phase: "fundamentos", path: "js", status: "planned",
    title: "Primeiros passos com JavaScript",
    desc: "Seu primeiro console.log(), como ler erros e criar o hábito de experimentar.",
    topics: ["console.log", "Erros", "Experimentar"] },

  // ---- JS básico ----
  { n: "04", slug: "valores-e-tipos", phase: "js-basico", path: "js", status: "planned",
    title: "Valores e tipos",
    desc: "Primitivos, objetos e o modelo mental de como o JavaScript enxerga dados.",
    topics: ["string", "number", "boolean", "null", "undefined"] },
  { n: "05", slug: "variaveis", phase: "js-basico", path: "js", status: "planned",
    title: "Variáveis: let, const, var",
    desc: "Guardar e nomear valores, e por que a escolha da declaração importa.",
    topics: ["let", "const", "var", "hoisting"] },
  { n: "06", slug: "operadores-e-coercao", phase: "js-basico", path: "js", status: "planned",
    title: "Operadores e coerção",
    desc: "Igualdade, truthy/falsy, short-circuit e a coerção que confunde todo iniciante.",
    topics: ["==", "===", "coerção", "truthy/falsy"] },
  { n: "07", slug: "igualdade-e-strict", phase: "js-basico", path: "js", status: "planned",
    title: "Igualdade e modo estrito",
    desc: "Os quatro algoritmos de igualdade do JavaScript, Object.is e o que 'use strict' muda.",
    topics: ["Object.is", "SameValue", "NaN / ±0", "use strict"] },
  { n: "08", slug: "condicionais", phase: "js-basico", path: "js", status: "planned",
    title: "Condicionais",
    desc: "Tomar decisões no código com if, else, switch e o operador ternário.",
    topics: ["if / else", "switch", "ternário"] },
  { n: "09", slug: "loops", phase: "js-basico", path: "js", status: "planned",
    title: "Loops",
    desc: "Repetir trabalho de forma controlada com for, while, for...of e for...in.",
    topics: ["for", "while", "for...of", "break"] },
  { n: "10", slug: "funcoes", phase: "js-basico", path: "js", status: "planned",
    title: "Funções",
    desc: "Declaração, expressão, arrow, parâmetros, retorno e funções como valores.",
    topics: ["arrow", "parâmetros", "retorno", "callbacks"] },

  // ---- JS intermediário ----
  { n: "11", slug: "arrays", phase: "js-inter", path: "js", status: "planned",
    title: "Arrays",
    desc: "Coleções ordenadas e os métodos que transformam dados sem loops manuais.",
    topics: ["map", "filter", "reduce", "find"] },
  { n: "12", slug: "objetos", phase: "js-inter", path: "js", status: "planned",
    title: "Objetos",
    desc: "Propriedades, métodos, referências, cópia e destructuring.",
    topics: ["propriedades", "referências", "destructuring", "spread"] },
  { n: "13", slug: "strings", phase: "js-inter", path: "js", status: "planned",
    title: "Strings",
    desc: "Manipulação de texto, template literals, unicode e encoding.",
    topics: ["template literals", "métodos", "unicode"] },
  { n: "14", slug: "escopo-e-closures", phase: "js-inter", path: "js", status: "planned",
    title: "Escopo e closures",
    desc: "Escopo léxico, shadowing e o modelo mental por trás das closures.",
    topics: ["escopo léxico", "closures", "shadowing"] },
  { n: "15", slug: "o-this-e-binding", phase: "js-inter", path: "js", status: "planned",
    title: "O this e binding",
    desc: "Quem é o this em cada contexto, e como call, apply e bind controlam isso.",
    topics: ["this", "call / apply", "bind", "arrow vs função"] },
  { n: "16", slug: "construtoras-e-fabricas", phase: "js-inter", path: "js", status: "planned",
    title: "Construtoras e fábricas",
    desc: "Funções construtoras com new, o padrão factory e quando preferir cada um.",
    topics: ["new", "função construtora", "factory", "this"] },
  { n: "17", slug: "prototipos-e-classes", phase: "js-inter", path: "js", status: "planned",
    title: "Protótipos e classes",
    desc: "A cadeia de protótipos, herança prototipal e a sintaxe de classes.",
    topics: ["prototype chain", "class", "extends", "super"] },
  { n: "18", slug: "erros", phase: "js-inter", path: "js", status: "planned",
    title: "Tratamento de erros",
    desc: "throw, try/catch/finally e como criar erros customizados úteis.",
    topics: ["try/catch", "throw", "Error", "customizados"] },
  { n: "19", slug: "modulos", phase: "js-inter", path: "js", status: "planned",
    title: "Módulos",
    desc: "Organizar código com ESM e CommonJS, imports dinâmicos e interoperabilidade.",
    topics: ["ESM", "CommonJS", "import", "export"] },

  // ---- Runtime & internals ----
  { n: "20", slug: "execution-context", phase: "js-runtime", path: "js", status: "planned",
    title: "Execution context & call stack",
    desc: "Como o JavaScript monta e empilha contextos de execução — visualizado passo a passo.",
    topics: ["call stack", "lexical env", "environment records"] },
  { n: "21", slug: "event-loop", phase: "js-runtime", path: "js", status: "planned",
    title: "Event loop, tasks & microtasks",
    desc: "Por que JavaScript é single-thread mas parece fazer várias coisas ao mesmo tempo.",
    topics: ["event loop", "task queue", "microtasks"] },
  { n: "22", slug: "promises-async-await", phase: "js-runtime", path: "js", status: "planned",
    title: "Promises e async/await",
    desc: "Do callback hell às promises, chaining, async/await e erros assíncronos.",
    topics: ["Promise", "async/await", "Promise.all"] },
  { n: "23", slug: "iterators-generators", phase: "js-runtime", path: "js", status: "planned",
    title: "Iterators, generators & symbols",
    desc: "O protocolo de iteração, funções que pausam e o poder dos symbols.",
    topics: ["iterators", "generators", "Symbol"] },
  { n: "24", slug: "proxies-colecoes", phase: "js-runtime", path: "js", status: "planned",
    title: "Proxies, Reflect & coleções",
    desc: "Interceptar operações e as estruturas Map, Set, WeakMap e WeakSet.",
    topics: ["Proxy", "Reflect", "Map / Set", "WeakMap"] },
  { n: "25", slug: "memoria-gc", phase: "js-runtime", path: "js", status: "planned",
    title: "Memória & garbage collection",
    desc: "Como valores vivem na memória, referências e quando o GC libera espaço.",
    topics: ["heap", "referências", "garbage collection"] },

  // ---- Web Platform ----
  { n: "26", slug: "dom-e-eventos", phase: "web", path: "js", status: "planned",
    title: "DOM e eventos",
    desc: "A árvore DOM, seleção e criação de elementos, bubbling, capturing e delegation.",
    topics: ["DOM", "eventos", "delegation"] },
  { n: "27", slug: "web-apis", phase: "web", path: "js", status: "planned",
    title: "Web APIs",
    desc: "Fetch, Storage, URL, History, Web Workers e WebSockets no navegador.",
    topics: ["Fetch", "Storage", "Workers", "WebSockets"] },
  { n: "28", slug: "devtools-debugging", phase: "web", path: "js", status: "planned",
    title: "DevTools e depuração",
    desc: "Breakpoints, inspeção de escopo, os métodos do console e a mentalidade de caçar bugs.",
    topics: ["breakpoints", "console", "step", "memory leaks"] },

  // ---- TypeScript fundamental ----
  { n: "29", slug: "intro-typescript", phase: "ts-fund", path: "ts", status: "planned",
    title: "Introdução ao TypeScript",
    desc: "Por que tipos existem, o relacionamento com JavaScript, tsconfig e compilação.",
    topics: ["tsconfig", "compilação", "type checking"] },
  { n: "30", slug: "tipos-fundamentais", phase: "ts-fund", path: "ts", status: "planned",
    title: "Tipos fundamentais",
    desc: "Annotations, inferência, tipos primitivos, arrays, tuples e literais.",
    topics: ["annotations", "inferência", "tuples", "literais"] },
  { n: "31", slug: "enums", phase: "ts-fund", path: "ts", status: "planned",
    title: "Enums",
    desc: "Enums numéricos e de string, const enum e quando preferir uma união de literais.",
    topics: ["enum", "const enum", "string enum", "union vs enum"] },
  { n: "32", slug: "any-unknown-never", phase: "ts-fund", path: "ts", status: "planned",
    title: "any, unknown, never & void",
    desc: "Os tipos especiais do TypeScript e quando cada um é a escolha certa.",
    topics: ["any", "unknown", "never", "void"] },

  // ---- TypeScript intermediário ----
  { n: "33", slug: "interfaces-e-tipos", phase: "ts-inter", path: "ts", status: "planned",
    title: "Interfaces, tipos & unions",
    desc: "Modelar objetos com interfaces e aliases, unions, intersections e literais.",
    topics: ["interface", "union", "intersection", "literais"] },
  { n: "34", slug: "classes-oop", phase: "ts-inter", path: "ts", status: "planned",
    title: "Classes e OOP",
    desc: "Modificadores de acesso, readonly, herança, polimorfismo, abstract e implements.",
    topics: ["public/private", "abstract", "extends", "implements"] },
  { n: "35", slug: "narrowing", phase: "ts-inter", path: "ts", status: "planned",
    title: "Funções & narrowing",
    desc: "Type guards, discriminated unions, overloads e refinamento de tipos.",
    topics: ["type guards", "narrowing", "discriminated unions"] },
  { n: "36", slug: "generics", phase: "ts-inter", path: "ts", status: "planned",
    title: "Generics",
    desc: "Tipos parametrizados, constraints, keyof, typeof e indexed access.",
    topics: ["generics", "constraints", "keyof", "typeof"] },
  { n: "37", slug: "overloading-satisfies", phase: "ts-inter", path: "ts", status: "planned",
    title: "Overloading, predicados & satisfies",
    desc: "Sobrecarga de funções, type predicates (x is T), satisfies, as const e non-null !.",
    topics: ["overload", "x is T", "satisfies", "as const"] },

  // ---- TypeScript avançado ----
  { n: "38", slug: "conditional-mapped", phase: "ts-avancado", path: "ts", status: "planned",
    title: "Conditional & mapped types",
    desc: "Tipos que decidem e transformam outros tipos — a base do type-level.",
    topics: ["conditional types", "mapped types", "as const"] },
  { n: "39", slug: "template-infer", phase: "ts-avancado", path: "ts", status: "planned",
    title: "Template literal types & infer",
    desc: "Compor e extrair tipos a partir de strings e estruturas com infer.",
    topics: ["template literals", "infer", "distributive"] },
  { n: "40", slug: "type-level", phase: "ts-avancado", path: "ts", status: "planned",
    title: "Type-level programming",
    desc: "Recursive types, branded types e padrões de nominal typing.",
    topics: ["recursive", "branded types", "nominal"] },
  { n: "41", slug: "utility-types", phase: "ts-avancado", path: "ts", status: "planned",
    title: "Utility types & bibliotecas",
    desc: "Utility types, declaration merging, module augmentation e API design.",
    topics: ["utility types", "declaration files", "satisfies"] },
  { n: "42", slug: "decorators", phase: "ts-avancado", path: "ts", status: "planned",
    title: "Decorators",
    desc: "Decorators de classe, método e propriedade: a sintaxe @, usos e o padrão moderno.",
    topics: ["@decorator", "classe", "método", "metadata"] },

  // ---- Aplicado & projeto ----
  { n: "43", slug: "declaracoes-namespaces", phase: "ts-aplicado", path: "ts", status: "planned",
    title: "Namespaces & arquivos de declaração",
    desc: "Namespaces, arquivos .d.ts ambient, declaration merging e augmentation de módulos e do escopo global.",
    topics: ["namespace", ".d.ts", "declaration merging", "augmentation"] },
  { n: "44", slug: "typescript-real", phase: "ts-aplicado", path: "ts", status: "planned",
    title: "TypeScript no mundo real",
    desc: "APIs, validação de dados, backend, tooling e o compilador nativo em Go (TS 7).",
    topics: ["APIs", "validação", "tooling", "TS 7 / tsgo"] },
  { n: "45", slug: "projeto-final", phase: "ts-aplicado", path: "ts", status: "planned",
    title: "Projeto final",
    desc: "Reunir JavaScript, runtime e TypeScript em uma aplicação completa do zero.",
    topics: ["arquitetura", "testes", "projeto completo"] },
];

/* Mapa de conhecimento — nós interligados (teaser da árvore de conhecimento) */
LEXICO.knowledgeMap = [
  "Closures", "Escopo léxico", "Call stack", "Event loop", "Promises",
  "Prototype chain", "Coerção", "Generics", "Narrowing", "Conditional types",
  "Mapped types", "Type-level", "Referências", "Garbage collection", "Iterators",
];
